/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Yury Misiyuk (https://sketchfab.com/Tim0)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cosmonaut-on-a-rocket-e93cbbdb9a2144fb9f63d062566f3e63
Title: Cosmonaut on a rocket
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import rocketScene from "../assets/3d/rocket.glb";

const Rocket = ({ isRotating, ...props }) => {
  const group = useRef();
  const { scene, animations } = useGLTF(rocketScene);
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (isRotating) {
      actions["Take 001"].play();
    } else {
      actions["Take 001"].stop();
    }
  }, [actions, isRotating]);

  return (
    <group {...props} ref={group} position={[0, -2, -4]} scale={[0.01, 0.01, 0.01]} rotation={[Math.PI/8, -Math.PI/10, 0]} >
      <primitive object={scene} />
    </group>
  );
};

export default Rocket;

