/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: AjaxGb (https://sketchfab.com/ajaxgb)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/extracted-minecraft-java-editions-stars-c8868b7ffc4a473eb5cd9203a59e3650
Title: [Extracted] Minecraft Java Edition's Stars
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

import spaceScene from "../assets/3d/space.glb";


export function Space({ isRotating }) {
  const space = useGLTF(spaceScene);
  const spaceRef = useRef();

  useFrame((_, delta) => {
    if (isRotating) {
      spaceRef.current.rotation.y += 0.25 * delta; 
    }
  });

  return (
    <mesh ref={spaceRef}>
      <primitive object={space.scene} />
    </mesh> 
  );
}

export default Space;